### ISSUE TITLE
Missing "Vac Allocated" data

### ISSUE THREAD

**Issue by nathakits** [djay/covidthailand#115]
Hi. In the `vac_timeline.csv` file, there are now only 2 vaccines for the "Vac Allocated" data. 
- Vac Allocated AstraZeneca
- Vac Allocated Sinovac

Before there was also `Pfizer` and `Sinopharm`.

Also the "Vac Allocated" data now has lots of empty/missing values, starting from `date":"2021-07-02`.

**Comment by reduxionist** [comment]
I was able to find the appropriate filename to create the test with via:
```
covidthailand/inputs/vaccinations ➜ pdfgrep '2 กันยายน 2564' * | cut -d: -f 1 | sort | uniq -c | sort -nr | awk '(NR==1){print $2}'
```
I am attempting to debug it now...

**Comment by reduxionist** [comment]
Oops, that was I confused July for September. Correct command to find the file is:
```
covidthailand/inputs/vaccinations [I] ➜ pdfgrep ' 2 กรกฎาคม 2564' * | cut -d: -f 1 | sort | uniq -c | sort -nr | awk '(NR==1){print $2}'
```
My apologies for the confusion.

**Comment by reduxionist** [comment]
@nathakits 

1. While some of the vaccination data sources do break it down by more than Sinovac and AstraZeneca, the government data in inputs/vaccinations/*.pdf do not. We may use the most reliable (i.e. found to consistently provide data) sources rather than the most detailed ones when those more detailed ones are less reliable.

2. As you can see from the MOPH file inputs/vaccinations/1625137453551.pdf, Sinovac and AstraZeneca numbers were broken down for 2021-07-01, but in inputs/vaccinations/1625377924615.pdf you can see they are no longer doing so as of 2021-07-02. This change in formatting may be responsible for the missing values after that point, I wouldn't have time to investigate further until the weekend.

**Comment by reduxionist** [comment]
@nathakits: If you can tell us exactly where there used to be data that now there isn't then I'll re-investigate, but do read my last explanations two comments above this one...

**Comment by reduxionist** [comment]
No problem @nathakits , just let me know if there's any further detail I can provide...
