### ISSUE TITLE
Improve legends

### ISSUE THREAD

**Issue by modiholodri** [djay/covidthailand#168]
Improve the legends without changing their meaning by....

- [x] Remove not needed things.
- [x] Standardize the word order.
- [x] Move giant legends into the footnotes and make the shorter in the legend.
- [x] Replace short words with full words.

**Comment by djay** [comment]
@modiholodri not sure on moving the health district legends to the footer. Wouldn't that just make the footer so much bigger than there is less room for the plot?

Related is that I want to start replacing some of the health district plots with 7 region based ones - #42 This should be more useful to see trends since bangkok gets included with surrounding provinces. But I guess the same problem exists in where to define which provinces are in which region? Maybe both plots should point to a source than can be googled?

**Comment by modiholodri** [comment]
@djay  According to my plan the size of the plot (chart) should be the same. The height of the footer is now calculated separate and should increase the overall height of the figure.  The font in the footer is smaller and there would be no need to abbreviate districts anymore.  The idea is also to replace UpN with Upper North and get rid of the numbers in the legends. Keep them in the footer if needed.

If the number of legend entries is reduced from 13 to 7 than it looks like that the problem will get even bigger if that stuff is in the legend, but could be smaller if it is in the footer, because of smaller font, longer lines... and 7 lines in the footer don't seem too bad...

I would say that it'll improve the situation, but for sure not be perfect. Another option could be also to put a little colored map over the plot. That might involve a little bit guessing for the boarder areas, but should give you a pretty good picture of there stuff is going one. Maybe also no good... 

![image](https://user-images.githubusercontent.com/9023241/140029574-aac90b5c-c1b1-417a-bbfb-c4de5dadd6dc.png)

**Comment by djay** [comment]
@modiholodri The number is the health district number which should not be dropped but explained. https://en.wikipedia.org/wiki/Healthcare_in_Thailand
The history behind using that is the first data I was trying to get was the test reports and the only geographic breakdown they had was by health district. So I continued using that even though it's less commonly known.

Using 7 regions I don't think I'd list the provinces since it's perhaps more well known division? or just point to a url where its defined? 
Well 5 regions is perhaps more well known (see https://en.wikipedia.org/wiki/Regions_of_Thailand) but I think for our purposes we need bangkok metropolitan region as seperate from central.

Using a map is a nice idea but I'm not sure it it helps that much more than the words?
BTW, here is one way CCSA used to divide up numbers
![Screen Shot 2021-11-03 at 4 04 47 pm](https://user-images.githubusercontent.com/41700/140033901-cd933fb3-7b65-4f5f-a26c-9f8a82dfea82.png)

**Comment by modiholodri** [comment]
@djay  Yeah, it's hard to say. I like the metrological regions and they might make also the most sense for viruses. With Bangkok (own climate anyway) added, they would look pretty good for me. The south is a little bit too long but if the climate is similar the seasonal spreading behavior in the whole region could be also similar. The map could be very small and there is no need the show the districts in there. If the colors are the same as in the legend then it makes it pretty clear which areas the plot is about.

![image](https://user-images.githubusercontent.com/9023241/140040602-1d5163e3-d60a-4333-b12d-66664802cfeb.png)

**Comment by djay** [comment]
@modiholodri the weather on the coasts of the south is very different. I don't think covid is. The briefing reports now days tend to divide up by 12 southern border regions, Bangkok region and then everything else. But that kind of division is temporary I think so not useful.

weirdly not a lot of maps to be found of the 7 regions 
![image](https://user-images.githubusercontent.com/41700/140255910-5053d4cd-50c7-458f-b197-162fc95de727.png)
![image](https://user-images.githubusercontent.com/41700/140255992-482a2148-df34-4dc5-92f8-50a40efd165a.png)

actually this is really nice with the shadings to show provinces. not sure how well it scales down small though 
![image](https://user-images.githubusercontent.com/41700/140256798-9f8f3fc0-7da2-4aab-ac3c-c29ceea449ae.png)

oh crap. that gets rid of West so yet another definition :(

**Comment by modiholodri** [comment]
@djay Agree that the last one looks best. The plots are quite a high resolution, so it still might be quite Ok scale it down after getting rid of all the province names. Looks also like RedEyeThai.com isn't active anymore, so there should be no problem with "borrowing" it...
