### ISSUE TITLE
Deaths 2024 is missing from Excess Deaths - Thailand 

### ISSUE THREAD

**Issue by modiholodri** [djay/covidthailand#296]
![image](https://github.com/djay/covidthailand/assets/9023241/eb7ff0bd-ac1c-4b55-b29c-fa65027410b7)

**Comment by djay** [comment]
@modiholodri fixed

**Comment by modiholodri** [comment]
> @modiholodri fixed

@djay  I still find it interesting how the overall situation is progressing and there was a peak a couple of months ago.

**Comment by djay** [comment]
@modiholodri the peak in excess deaths in april I'd be 99% sure was due to the heat wave. Same reason there was a spike in excess deaths in April 2016. 
But what is keeping the deaths higher than pre-pandemic numbers generally I'm not sure about. In terms of trying to work out how much covid is out there the only number that I think gives an indication anymore is the hospitalised on ventilator number since there  doesn't seem to be much testing of deaths or mild cases.
It might be interesting to see if what the correlation is between excess deaths and the ventilator number

![image](https://github.com/djay/covidthailand/assets/41700/c672ffe2-1361-42e9-b45f-e6e325c57c81)

**Comment by modiholodri** [comment]
@djay Yes, completely agree with you that the heat wave had a big impact. I would not blame it for 99% but still a considerable portion. May was also very hot (just according to my feeling), and the numbers are very close to last year. Maybe wait until the end of the year to see if there is some pattern emerging…

**Comment by djay** [comment]
@modiholodri well there is an effect of the first part of a wave killing those that were not doing well already and then there being less of them afterwards. also people change their behaviour and relatives and the government also. So I can see why there might be more deaths at the start of a heat wave than at the end rather than a pure correlation with temperature.

**Comment by modiholodri** [comment]
@djay Yes, correlations are probably most of the time not pure. Anyway, good that the numbers get updated again.👍
