### ISSUE TITLE
better y axis fomatting

### ISSUE THREAD

**Issue by djay** [djay/covidthailand#86]
- [x] [human_format](https://github.com/djay/covidthailand/blob/45ab729d5cdba862de2c5940264f790a5504907a/utils_pandas.py#L98-L98) has an extra ".0" sometimes which takes up space
- [x] many y axis aren't labelled. Maybe not all need to be but some its unclear
- [x] thaipopulation formatter takes up too much space
- [x] can use % formatter more
- [x] maybe replace right hand side formatter with labelling the values of the specific lines. since latest date is normally the most interesting

**Comment by djay** [comment]
@modiholodri not sure why I can't assign it either

**Comment by reduxionist** [comment]
Can only assign issues to Contributors...

**Comment by modiholodri** [comment]
@djay I started working on the chart layout and made some progress already.  There are more changes, so I guess I should make separate PRs for each of them or just make separate commits in one PR?
There are some changes where you might have a different option/taste like...
- All legends are in the upper left corner. I think it's the best place and nice if it is consistent in all charts. Even if it is not the perfect place for some of the charts.
- No Y axis labels are needed. What is shown should be clear from the title and if not then the title should be improved.
- All legends are written with the same font size.
- Some fonts are a little smaller.
- Added tick marks, so that the X and Y axis labels don't overlap at the 0 point.
- Removed CC-BY for now, should be added in the footer.
- The original source could be added in the footer...

Anything what is against your taste/idea?

That's how it looks at the moment (still a work in progress)... 
![image](https://user-images.githubusercontent.com/9023241/135564225-99972bb0-a99f-42ca-8e03-295e179f7ee1.png)

**Comment by djay** [comment]
> make separate PRs for each of them or just make separate commits in one PR?

yeah I think thats better. unless they are rely on each other someway I guess

The no decimals looks great. And it also works for charts where they need decimals?





> * All legends are in the upper left corner. I think it's the best place and nice if it is consistent in all charts. Even if it is not the perfect place for some of the charts.

There are lots of charts where it doesn't work in that location. There is a way to fix it per plot and maybe all the province ones it makes sense to always prefer it there? but I think some of the health district area charts it doesn't work there. Also keep in mind that it generates 4-5 different time periods for every plot so some may more in that location better than others.


> * No Y axis labels are needed. What is shown should be clear from the title and if not then the title should be improved.

ok great.


> * Removed CC-BY for now, should be added in the footer.

you are right. maybe even the url too?
there are a lot of caveats in the readme that would be good to simplify and put into the footnotes section not that it exists. Another thing I was thinking is putting in the url to actual source as well as our url?


> * The original source could be added in the footer...

ah one step ahead of me :)

**Comment by modiholodri** [comment]
Yes, it works also for charts with decimals.  I had just a few examples, because I am somehow having issues with the settings about what to produce (had to hardcode it because I'm too stupid to make the work with the settings file and did not bother to look up the details yet).  Once it exported 250+ charts, but now it gets stuck around 60...😒

![image](https://user-images.githubusercontent.com/9023241/135570279-158f5c3f-15f1-4363-a2ee-945809d4aafd.png)

The X axis still need more fixing... 

I would say the URL in there is good and makes it somehow more balanced. And if others reuse the charts everybody knows from where they comes from.

To put all the need info in the chart is nice and then every picture would be self-contained.

**Comment by djay** [comment]
Awesome. thats looking great.

**Comment by reduxionist** [comment]
Since all tasks in this issue have merged PRs in them, I think it can be closed no? Learning tip: if a PR would resolve a particular issue writing
```
(fixes|closes) #X
```
in the PR will let GH auto-close the related issue once the PR in question is merged, neat huh? :smiley:

Thanks for all your contribs  @modiholodri; hope you make it in as one of the first 50k hacktoberfestists because you definitely deserve it!

**Comment by modiholodri** [comment]
@reduxionist Welcome! :-)
The thaipopulation formatter is not fixed yet. I'll do it this week some time.

**Comment by reduxionist** [comment]
เมื่อ อ. 5 ต.ค. 2564 เวลา 08:37 Reinhold Lauer ***@***.***>
เขียนว่า:

> @reduxionist <https://github.com/reduxionist> Welcome! :-)
> The thaipopulation formatter is not fixed yet. I'll do it this week some
> time.
>

Okay cool, no rush! 😀

**Comment by djay** [comment]
I noticed a few graphs are % ones like vaccinations so would be good to have % formatter on those?

**Comment by modiholodri** [comment]
@djay Noticed that also already. The basic plan is to make this week second round concerning the charts.

- Thai population formatter
- % where applicable
- Original Source
- Foot notes
- Improve titles
- ...

Have to try also to fetch everything again so that all the charts are produced. Last time it got stuck after 58 charts...

**Comment by djay** [comment]
yep. closing now. feel free to create specific tickets for the things you propose to do. try to title about what its trying to fix more than how its going to fix it.
